// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "unio";



        [DllImport(__DllName, EntryPoint = "delete_read_result", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void delete_read_result(ReadResult value);

        [DllImport(__DllName, EntryPoint = "delete_byte_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void delete_byte_buffer(ByteBuffer bytes);

        [DllImport(__DllName, EntryPoint = "delete_error", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void delete_error(UnioError* error);

        [DllImport(__DllName, EntryPoint = "unio_file_read_to_end", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ReadResult unio_file_read_to_end(ushort* path, int path_length);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ReadResult
    {
        public ByteBuffer bytes;
        public UnioError* error;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ByteBuffer
    {
        public byte* ptr;
        public int length;
        public int capacity;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct UnioError
    {
        public String message;
    }



}
